# Generated by Django 6.0.5 on 2026-05-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesystem', '0001_initial'),
        ('jobs', '0001_initial'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=60)),
                ('max_level', models.PositiveIntegerField(default=100)),
                ('xp_curve', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('software_type', models.CharField(choices=[('firewall', 'Firewall'), ('waterwall', 'Waterwall'), ('cracker', 'Cracker'), ('miner', 'Miner'), ('webserver', 'Webserver'), ('utility', 'Utility'), ('app_package', 'App Package')], max_length=40)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('base_stats', models.JSONField(blank=True, default=dict)),
                ('transferable', models.BooleanField(default=True)),
                ('file_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_file', to='filesystem.filenode')),
                ('locked_by_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_software', to='jobs.persistedjob')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_files', to='machines.machine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSoftwareSelection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_slug', models.SlugField(max_length=60)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_software', to='machines.machine')),
                ('software_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_selections', to='software.softwarefile')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareUpgradeRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('software_type', models.CharField(choices=[('firewall', 'Firewall'), ('waterwall', 'Waterwall'), ('cracker', 'Cracker'), ('miner', 'Miner'), ('webserver', 'Webserver'), ('utility', 'Utility'), ('app_package', 'App Package')], max_length=40)),
                ('target_level', models.PositiveIntegerField()),
                ('required_xp', models.PositiveIntegerField()),
                ('modifiers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('software_type', 'target_level'), name='unique_upgrade_rule')],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to='machines.machine')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to='software.skilldefinition')),
                ('software_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to='software.softwarefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='software.skilldefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='unique_skill_progress_per_user')],
            },
        ),
        migrations.AddIndex(
            model_name='softwarefile',
            index=models.Index(fields=['machine', 'software_type'], name='software_so_machine_8de985_idx'),
        ),
        migrations.AddIndex(
            model_name='softwarefile',
            index=models.Index(fields=['owner', 'software_type'], name='software_so_owner_i_07c727_idx'),
        ),
        migrations.AddConstraint(
            model_name='activesoftwareselection',
            constraint=models.UniqueConstraint(fields=('machine', 'app_slug'), name='unique_active_software_per_app'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', 'created_at'], name='software_xp_user_id_b6d58c_idx'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['source', 'created_at'], name='software_xp_source_f37f30_idx'),
        ),
    ]
