# Generated by Django 6.0.5 on 2026-05-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('rule', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardwareSlotDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliverySubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardwareCatalogItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('motherboard', 'Motherboard'), ('ram', 'RAM'), ('hdd', 'HDD'), ('ssd', 'SSD'), ('usb', 'USB Stick'), ('case', 'Case'), ('pear_chip', 'Integrated Pear Chip')], max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('slot_requirements', models.JSONField(blank=True, default=dict)),
                ('compatibility_tags', models.JSONField(blank=True, default=list)),
                ('physical', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'price', 'name'],
                'indexes': [models.Index(fields=['category', 'price'], name='hardware_ha_categor_4a8c10_idx')],
            },
        ),
        migrations.CreateModel(
            name='HardwareItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('inventory', 'Inventory'), ('equipped', 'Equipped'), ('listed', 'Listed'), ('delivering', 'Delivering'), ('sold', 'Sold')], default='inventory', max_length=20)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='hardware.hardwarecatalogitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquippedHardware',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=60)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_hardware', to='machines.machine')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_record', to='hardware.hardwareitem')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('eta', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('speed', models.CharField(default='normal', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='machines.machine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='hardware.hardwarecatalogitem')),
                ('hardware_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='hardware.hardwareitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='available', max_length=20)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_record', to='hardware.hardwareitem')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_type', models.CharField(max_length=60)),
                ('count', models.PositiveIntegerField(default=1)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_slots', to='hardware.hardwarecatalogitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='hardwareitem',
            index=models.Index(fields=['owner', 'status'], name='hardware_ha_owner_i_55493e_idx'),
        ),
        migrations.AddIndex(
            model_name='equippedhardware',
            index=models.Index(fields=['machine', 'slot'], name='hardware_eq_machine_ead1c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='equippedhardware',
            constraint=models.UniqueConstraint(fields=('machine', 'slot'), name='unique_equipped_slot_per_machine'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['owner', 'status', 'eta'], name='hardware_de_owner_i_dd5c55_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['machine', 'status'], name='hardware_in_machine_fbc939_idx'),
        ),
    ]
