# Generated by Django 6.0.5 on 2026-05-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompatibilityRule',
        ),
        migrations.DeleteModel(
            name='HardwareSlotDefinition',
        ),
        migrations.RemoveField(
            model_name='hardwarecatalogitem',
            name='compatibility_tags',
        ),
        migrations.RemoveField(
            model_name='hardwarecatalogitem',
            name='physical',
        ),
        migrations.RemoveField(
            model_name='hardwarecatalogitem',
            name='slot_requirements',
        ),
        migrations.DeleteModel(
            name='MotherboardSlot',
        ),
    ]
