# Generated by Django 6.0.5 on 2026-05-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_delete_compatibilityrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareitem',
            name='status',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('equipped', 'Equipped'), ('listed', 'Listed'), ('delivering', 'Delivering'), ('sold', 'Sold'), ('trash', 'Trash')], default='inventory', max_length=20),
        ),
    ]
