# Generated by Django 6.0.5 on 2026-05-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('default_display_name', models.CharField(max_length=80)),
                ('os_display_names', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(max_length=40)),
                ('is_core', models.BooleanField(default=False)),
                ('is_uninstallable', models.BooleanField(default=True)),
                ('required_permissions', models.JSONField(blank=True, default=list)),
                ('icon_key', models.CharField(max_length=80)),
                ('default_install_rules', models.JSONField(blank=True, default=dict)),
                ('terminal_command_aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['category', 'default_display_name'],
            },
        ),
        migrations.CreateModel(
            name='OSDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('version', models.CharField(max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('availability', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('starter', 'Starter')], max_length=20)),
                ('modifiers', models.JSONField(blank=True, default=dict)),
                ('default_apps', models.JSONField(blank=True, default=list)),
                ('command_set_reference', models.CharField(blank=True, max_length=80)),
                ('manual_references', models.JSONField(blank=True, default=list)),
                ('allowed_window_managers', models.JSONField(blank=True, default=list)),
                ('acquisition_rules', models.JSONField(blank=True, default=dict)),
                ('company_site', models.CharField(max_length=120)),
                ('terminal_style', models.CharField(max_length=40)),
                ('theme_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('hostname', models.SlugField(max_length=64)),
                ('fictional_ip', models.CharField(max_length=45, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('powered_on', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppInstall',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installs', to='machines.appdefinition')),
                ('installed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_installs', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_installs', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineStatSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processing_power', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cpu_power', models.DecimalField(decimal_places=4, max_digits=14)),
                ('gpu_power', models.DecimalField(decimal_places=4, max_digits=14)),
                ('memory_gb', models.DecimalField(decimal_places=4, max_digits=14)),
                ('storage_gb', models.DecimalField(decimal_places=4, max_digits=14)),
                ('mining_efficiency', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cracking_efficiency', models.DecimalField(decimal_places=4, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_snapshots', to='machines.machine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OSInstall',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_manager', models.CharField(blank=True, max_length=80)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('installed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='os_installs', to=settings.AUTH_USER_MODEL)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installed_os', to='machines.machine')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installs', to='machines.osdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='MachinePreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(default='default', max_length=60)),
                ('desktop_settings', models.JSONField(blank=True, default=dict)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='machines.machine')),
                ('active_os_install', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='machines.osinstall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['owner'], name='machines_ma_owner_i_a811a9_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['fictional_ip'], name='machines_ma_fiction_31fb7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(fields=('owner', 'hostname'), name='unique_machine_hostname_per_owner'),
        ),
        migrations.AddIndex(
            model_name='appinstall',
            index=models.Index(fields=['machine', 'active'], name='machines_ap_machine_19aeca_idx'),
        ),
        migrations.AddConstraint(
            model_name='appinstall',
            constraint=models.UniqueConstraint(fields=('machine', 'app'), name='unique_app_install_per_machine'),
        ),
        migrations.AddIndex(
            model_name='machinestatsnapshot',
            index=models.Index(fields=['machine', 'created_at'], name='machines_ma_machine_634858_idx'),
        ),
        migrations.AddIndex(
            model_name='osinstall',
            index=models.Index(fields=['machine', 'active'], name='machines_os_machine_05b7a6_idx'),
        ),
    ]
