# Generated by Django 6.0.5 on 2026-05-19 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopShortcut',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortcut_type', models.CharField(choices=[('app', 'App'), ('file', 'File')], max_length=10)),
                ('app_id', models.SlugField(blank=True, max_length=60, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('grid_x', models.IntegerField(default=0)),
                ('grid_y', models.IntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_shortcuts', to='machines.machine')),
            ],
            options={
                'ordering': ['grid_y', 'grid_x', 'created_at'],
                'indexes': [models.Index(fields=['machine'], name='machines_de_machine_5f6457_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('app_id__isnull', False)), fields=('machine', 'app_id'), name='unique_app_shortcut_per_machine'), models.UniqueConstraint(condition=models.Q(('file_path__isnull', False)), fields=('machine', 'file_path'), name='unique_file_shortcut_per_machine')],
            },
        ),
    ]
