# Generated by Django 6.0.5 on 2026-05-19 03:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_add_desktop_shortcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopWindowState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('windows', models.JSONField(blank=True, default=dict)),
                ('active_window_id', models.CharField(blank=True, max_length=255, null=True)),
                ('z_seed', models.IntegerField(default=0)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_window_state', to='machines.machine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
