# Generated by Django 6.0.5 on 2026-05-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_add_desktop_window_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='machinestatsnapshot',
            name='machines_ma_machine_634858_idx',
        ),
        migrations.RemoveField(
            model_name='appdefinition',
            name='default_install_rules',
        ),
        migrations.RemoveField(
            model_name='appdefinition',
            name='required_permissions',
        ),
        migrations.DeleteModel(
            name='MachineStatSnapshot',
        ),
    ]
