# Generated by Django 6.0.5 on 2026-05-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('machines', '0001_initial'),
        ('software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('difficulty', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='machines.machine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiningJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='cpu', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_payout', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('payout_settled_until', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mining_jobs', to='economy.coindefinition')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_jobs', to='machines.machine')),
                ('miner_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mining_jobs', to='software.softwarefile')),
                ('persisted_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mining_job', to='jobs.persistedjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_jobs', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mining_jobs', to='economy.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=24)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_balances', to='economy.coindefinition')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='economy.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='economy.coindefinition')),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='economy.wallet')),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='economy.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CoinPricePoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_at', models.DateTimeField()),
                ('price_credits', models.DecimalField(decimal_places=8, max_digits=18)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='economy.coindefinition')),
            ],
            options={
                'indexes': [models.Index(fields=['coin', 'price_at'], name='economy_coi_coin_id_5d3b49_idx')],
                'constraints': [models.UniqueConstraint(fields=('coin', 'price_at'), name='unique_coin_price_at')],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['owner'], name='economy_wal_owner_i_6dbfa3_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['address'], name='economy_wal_address_d76c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='miningjob',
            index=models.Index(fields=['machine', 'status'], name='economy_min_machine_f0d450_idx'),
        ),
        migrations.AddIndex(
            model_name='miningjob',
            index=models.Index(fields=['user', 'status'], name='economy_min_user_id_732dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletbalance',
            constraint=models.UniqueConstraint(fields=('wallet', 'coin'), name='unique_wallet_coin_balance'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['coin', 'created_at'], name='economy_wal_coin_id_c0803e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status', 'created_at'], name='economy_wal_status_2fc416_idx'),
        ),
    ]
