# Generated by Django 6.0.5 on 2026-05-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('path', models.CharField(max_length=1024)),
                ('kind', models.CharField(choices=[('directory', 'Directory'), ('file', 'File')], max_length=20)),
                ('file_type', models.CharField(blank=True, max_length=40)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField(blank=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_nodes', to='machines.machine')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='filesystem.filenode')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_read', models.BooleanField(default=True)),
                ('owner_write', models.BooleanField(default=True)),
                ('owner_execute', models.BooleanField(default=True)),
                ('public_read', models.BooleanField(default=False)),
                ('public_write', models.BooleanField(default=False)),
                ('public_execute', models.BooleanField(default=False)),
                ('privileged', models.BooleanField(default=False)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='filesystem.filenode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='filenode',
            index=models.Index(fields=['machine', 'path'], name='filesystem__machine_649147_idx'),
        ),
        migrations.AddIndex(
            model_name='filenode',
            index=models.Index(fields=['machine', 'parent'], name='filesystem__machine_f867d7_idx'),
        ),
        migrations.AddIndex(
            model_name='filenode',
            index=models.Index(fields=['owner'], name='filesystem__owner_i_b8fa27_idx'),
        ),
        migrations.AddConstraint(
            model_name='filenode',
            constraint=models.UniqueConstraint(fields=('machine', 'parent', 'name'), name='unique_node_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='filenode',
            constraint=models.UniqueConstraint(fields=('machine', 'path'), name='unique_node_path_per_machine'),
        ),
    ]
