# Generated by Django 6.0.5 on 2026-05-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistedJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('mining', 'Mining'), ('cracking', 'Cracking'), ('delivery', 'Delivery'), ('generic', 'Generic')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('retrying', 'Retrying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=20)),
                ('domain_object_type', models.CharField(blank=True, max_length=80)),
                ('domain_object_id', models.CharField(blank=True, max_length=80)),
                ('priority', models.IntegerField(default=100)),
                ('run_after', models.DateTimeField()),
                ('locked_by', models.CharField(blank=True, max_length=120)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persisted_jobs', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persisted_jobs', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='JobEventLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.persistedjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='persistedjob',
            index=models.Index(fields=['status', 'run_after', 'priority', 'locked_at'], name='jobs_persis_status_9cd702_idx'),
        ),
        migrations.AddIndex(
            model_name='persistedjob',
            index=models.Index(fields=['kind', 'status'], name='jobs_persis_kind_692d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='persistedjob',
            index=models.Index(fields=['machine', 'status'], name='jobs_persis_machine_2d584e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobeventlog',
            index=models.Index(fields=['job', 'created_at'], name='jobs_jobeve_job_id_b8dd73_idx'),
        ),
        migrations.AddIndex(
            model_name='jobeventlog',
            index=models.Index(fields=['event_type', 'created_at'], name='jobs_jobeve_event_t_3a1d8d_idx'),
        ),
    ]
