# Generated by Django 6.0.5 on 2026-05-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobeventlog',
            name='jobs_jobeve_job_id_b8dd73_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobeventlog',
            name='jobs_jobeve_event_t_3a1d8d_idx',
        ),
        migrations.DeleteModel(
            name='JobEventLog',
        ),
    ]
