# Generated by Django 6.0.5 on 2026-05-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('machines', '0001_initial'),
        ('software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FictionalIP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=45, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fictional_ip_record', to='machines.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimulatedRemoteSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions', to=settings.AUTH_USER_MODEL)),
                ('source_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions_started', to='machines.machine')),
                ('target_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions_received', to='machines.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrackJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_ip', models.CharField(max_length=45)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crack_jobs', to=settings.AUTH_USER_MODEL)),
                ('attacker_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_crack_jobs', to='machines.machine')),
                ('cracker_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crack_jobs', to='software.softwarefile')),
                ('persisted_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crack_job', to='jobs.persistedjob')),
                ('target_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_crack_jobs', to='machines.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['attacker', 'status'], name='networking__attacke_8a1da7_idx'), models.Index(fields=['target_machine', 'status'], name='networking__target__ca17e6_idx'), models.Index(fields=['target_ip', 'status'], name='networking__target__ad566a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimulatedLoginAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_ip', models.CharField(max_length=45)),
                ('succeeded', models.BooleanField(default=False)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulated_login_attempts', to=settings.AUTH_USER_MODEL)),
                ('source_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulated_login_attempts', to='machines.machine')),
                ('target_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulated_login_attempts_received', to='machines.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['target_machine', 'created_at'], name='networking__target__c61a90_idx'), models.Index(fields=['actor', 'created_at'], name='networking__actor_i_664b08_idx')],
            },
        ),
    ]
