# Generated by Django 6.0.5 on 2026-05-16 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedWebsite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('behavior_key', models.CharField(max_length=80)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('trust_level', models.CharField(default='trusted', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=253, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='machines.machine')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='browser.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('site_type', models.CharField(choices=[('predefined', 'Predefined'), ('user_hosted', 'User Hosted')], default='user_hosted', max_length=30)),
                ('trust_level', models.CharField(default='untrusted', max_length=30)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('sandbox_policy', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('content_version', models.PositiveIntegerField(default=1)),
                ('domain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website', to='browser.domain')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebserverConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='stopped', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webserver_config', to='machines.machine')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webserver_configs', to='browser.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchIndexEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('site_type', models.CharField(max_length=30)),
                ('trust_level', models.CharField(max_length=30)),
                ('predefined_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='browser.predefinedwebsite')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='browser.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteDeployment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_deployments', to='machines.machine')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='browser.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('content_type', models.CharField(default='text/html', max_length=80)),
                ('content', models.TextField(blank=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='browser.website')),
            ],
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['name'], name='browser_dom_name_117816_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['owner', 'status'], name='browser_dom_owner_i_f01024_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['domain', 'status'], name='browser_cer_domain__d6392c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['owner', 'status'], name='browser_cer_owner_i_e4a3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['owner', 'status'], name='browser_web_owner_i_1999e2_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['site_type', 'trust_level'], name='browser_web_site_ty_eb019a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindexentry',
            index=models.Index(fields=['domain', 'site_type', 'trust_level'], name='browser_sea_domain_efedac_idx'),
        ),
        migrations.AddConstraint(
            model_name='websitefile',
            constraint=models.UniqueConstraint(fields=('website', 'path'), name='unique_website_file_path'),
        ),
    ]
