# Generated by Django 6.0.5 on 2026-05-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebserverConfig',
        ),
    ]
